services:
  backend:
    build:
      context: src/backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: src/frontend
    ports:
      - "3000:3000"
    env_file:
      - src/backend/.env